name: PlayerHead
version: 1.3
main: Enes5519\PlayerHead\PlayerHead
api: 3.9.3
author: Enes5519

permissions:
  playerhead:
    description: Main permission
    default: op
    children:
      playerhead.give:
        default: op
      playerhead.spawn:
        default: op
      playerhead.attack:
        default: true
